src/java/model/Cart.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.DAOProduct;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hoang Long
 */
public class Cart {

    private List<Item> items;

    public Cart() {
        items = new ArrayList<>();
    }

    public List<Item> getItems() {
        return items;
    }

    private Item getItemById(int id,int sId, int mId ) {

        for (Item i : items) {
            if (i.getProduct().getId() == id && i.getProduct().getSize().getId() == sId && i.getProduct().getMat().getId() == mId) {
                return i;
            }
        }

        return null;
    }
    
    public int getQuantityById(int id,int sId, int mId ) {
        return getItemById(id,sId,mId).getQuantity();
    }

    public void addItem(Item i) {
        if (getItemById(i.getProduct().getId(),i.getProduct().getSize().getId(),i.getProduct().getMat().getId()) != null) {
            Item oldItem = getItemById(i.getProduct().getId(),i.getProduct().getSize().getId(),i.getProduct().getMat().getId());
            oldItem.setQuantity(oldItem.getQuantity() + i.getQuantity());
        } else {
            items.add(i);
        }
    }
    public static void main(String[] args) {
        DAOProduct dao = new DAOProduct();
        List<Product> list = dao.getAllProduct();
        Cart ca = new Cart("26:5:2:5/36:5:5:4/15:1:1:3/9:1:1:4/29:1:1:3/17:1:1:4/28:1:1:1/38:1:1:1/6:1:1:1/37:1:1:1", list);
        System.out.println(ca.getQuantityById(15, 1, 1));
        Product p = ca.getProductById(15, 1, 1, list);
        Item i = new Item(p, -1, p.getPrice());
        ca.addItem(i);
        System.out.println(ca.getQuantityById(15, 1, 1));
    }
    public void removeItem(int id,int sId, int mId) {
        if (getItemById(id,sId,mId) != null) {
            items.remove(getItemById(id,sId,mId));
        }
    }

    public double getTotalMoney() {
        double total = 0;

        for (Item i : items) {
            total += i.getQuantity() * i.getPrice();
        }

        return total;
    }

    private  Product getProductById(int pId,int sId, int mId, List<Product> list) {
        for (Product x : list) {
            if (x.getId() == pId && x.getSize().getId() == sId && x.getMat().getId() == mId) {
                return x;
            }
        }
        return null;
    }
    
    public Cart(String txt, List<Product> list) {
        items = new ArrayList<>();
        try {
            if (txt != null && txt.length() != 0) {
                String[] listP = txt.split("/");
                for (String p : listP) {
                    String[] info = p.split(":");
                    int pId = Integer.parseInt(info[0]);
                    int sId = Integer.parseInt(info[1]);
                    int mId = Integer.parseInt(info[2]);
                    int quantity = Integer.parseInt(info[3]);
                    Product product = getProductById(pId, sId, mId, list);
                    Item i = new Item(product, quantity, product.getPrice());
                    addItem(i);
                }
            }
        } catch (NumberFormatException e){
            
        }

    }
}

src/java/model/Product.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.util.List;

/**
 *
 * @author Hoang Long
 */
public class Product {
    private int id;
    private String name,description,image;
    private int quantity;
    private double price;
    private Account seller;
    private Category cate;
    private Size size;
    private Material mat;
    private int purchases;
    private List<Comment> comments;

    public List<Comment> getComments() {
        return comments;
    }

    public void setComments(List<Comment> comments) {
        this.comments = comments;
    }
    
    public int getPurchases() {
        return purchases;
    }
    public int getTotalComment(){
        return comments.size();
    }
    public void setPurchases(int purchases) {
        this.purchases = purchases;
    }
    
    public Product() {
    }

    public Product(int id, String name, String description, String image, int quantity, double price, Account seller, Category cate, Size size, Material mat) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.image = image;
        this.quantity = quantity;
        this.price = price;
        this.seller = seller;
        this.cate = cate;
        this.size = size;
        this.mat = mat;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Account getSeller() {
        return seller;
    }

    public void setSeller(Account seller) {
        this.seller = seller;
    }

    public Category getCate() {
        return cate;
    }

    public void setCate(Category cate) {
        this.cate = cate;
    }

    public Size getSize() {
        return size;
    }

    public void setSize(Size size) {
        this.size = size;
    }

    public Material getMat() {
        return mat;
    }

    public void setMat(Material mat) {
        this.mat = mat;
    }
    
    
    

    

    

    

    
    
    
}

web/cart.jsp
<%-- 
    Document   : cart
    Created on : 11-Jun-2023, 20:16:15
    Author     : Hoang Long
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="icon" href="img/icon.jpg" type="image/x-icon"/>
        <title>RiaShop- Your dream your world</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free HTML Templates" name="keywords">
        <meta content="Free HTML Templates" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <!-- Topbar Start --> 
        <%@include file="header.jsp" %>
        <!-- Topbar End -->


        <!-- Navbar Start -->
        <div class="container-fluid mb-5">
            <div class="row border-top px-xl-5">
                <div class="col-lg-3 d-none d-lg-block">
                    <%@include file="left-page.jsp" %>
                </div>
                <div class="col-lg-9">
                    <%@include file="right-page.jsp" %>
                </div>
            </div>
        </div>
        <!-- Navbar End -->
        <div class="container-fluid pt-5">
            <div class="row px-xl-5">
                <div class="col-lg-8 table-responsive mb-5">
                    <table class="table table-bordered text-center mb-0">
                        <thead class="bg-secondary text-dark">
                            <tr>
                                <th>No</th>
                                <th>Products</th>
                                <th>Price</th>

                                <th>Quantity</th>
                                <th>Total</th>
                                <th>Remove</th>
                            </tr>
                        </thead>
                        <tbody class="align-middle">
                            <c:set var="i" value="0"/>
                            <c:forEach items="${cart.items}" var="o" >
                                <tr>
                                    <c:set var="i" value="${i+1}"/>
                                    <td>${i}</td>
                                    <td class="align-middle"><img src="${o.product.image}" alt="" style="width: 50px;"> ${o.product.name}</td>
                                    <td class="align-middle">${o.price}$</td>

                                    <td class="align-middle">
                                        <div class="input-group quantity mx-auto" style="width: 100px;">
                                            <div class="input-group-btn">
                                                <a href="process?num=-1&pId=${o.product.id}&sizeId=${o.product.size.id}&matId=${o.product.mat.id}">
                                                    <button class="btn btn-sm btn-primary btn-minus" >
                                                        <i class="fa fa-minus"></i>
                                                    </button>
                                                </a>
                                            </div>
                                            <input type="text" readonly="" class="form-control form-control-sm bg-secondary text-center" value="${o.quantity}">
                                            <div class="input-group-btn">
                                                <a href="process?num=1&pId=${o.product.id}&sizeId=${o.product.size.id}&matId=${o.product.mat.id}">
                                                    <button class="btn btn-sm btn-primary btn-plus">
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle">${o.price*o.quantity}</td>
                                    <td class="align-middle">
                                        <form action="process" method="post">
                                            <input type="hidden" name="pId" value="${o.product.id}">
                                            <input type="hidden" name="sizeId" value="${o.product.size.id}">
                                            <input type="hidden" name="matId" value="${o.product.mat.id}">
                                            <input type="submit" value="x" class="btn btn-sm btn-primary"/>
                                        </form>
                                    </td>

                                </tr>
                            </c:forEach>    
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-4">

                    <div class="card border-secondary mb-5">
                        <div class="card-header bg-secondary border-0">
                            <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                        </div>
                        <div class="card-body">
                            <c:forEach items="${cart.items}" var="o" >
                                <div class="d-flex justify-content-between mb-3 pt-1">
                                    <h6 class="font-weight-medium">${o.product.name}</h6>
                                    <h6 class="font-weight-medium">${o.price*o.quantity}$</h6>
                                    
                                </div>
                            </c:forEach>

                        </div>
                        <div class="card-footer border-secondary bg-transparent">
                            <div class="d-flex justify-content-between mt-2">
                                <h5 class="font-weight-bold">Total</h5>
                                <h5 class="font-weight-bold">$ ${cart.totalMoney}</h5>
                            </div>
                            <<form action="checkout" method="post">
                                <input type="submit" value="Proceed To Checkout" class="btn btn-block btn-primary my-3 py-3"/>
                            </form>>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart End -->
        <%@include file="footer.jsp" %>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>

        <!-- Contact Javascript File -->
        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>

        <!-- Template Javascript -->
        <script src="js/main.js"></script>
    </body>
</html>

web/header-manage.jsp
<div class="row align-items-center py-3 px-xl-5">
    <div class="col-lg-3 d-none d-lg-block">
        <a href="home" class="text-decoration-none">
            <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">Ria</span>Shop</h1>
        </a>
    </div>
    <div class="col-lg-9 col-12 text-left">

        <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
            <a href="home" class="text-decoration-none d-block d-lg-none">
                <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">Ria</span>Shop</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">

                <c:if test="${sessionScope.acc != null}">
                    <div class="navbar-nav ml-auto py-0">

                        <div style="display: flex;justify-items: center;align-items: center">
                            <img style="height: 40px;border-radius: 50%;" src="${sessionScope.acc.info.avatar}" alt="avatar"/>
                        </div>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle active" data-toggle="dropdown">${sessionScope.acc.info.fullName}</a>
                            <div class="dropdown-menu dropdown-menu-right rounded-0 m-0">
                                <a href="user-detail" class="dropdown-item">Profile</a>
                                <a href="change-pass" class="dropdown-item">Change password</a>
                                <a href="logout" class="dropdown-item">Logout</a>
                            </div>
                        </div>
                    </div>
                </c:if>

            </div>
        </nav>
    </div>

</div>

web/header.jsp
<%-- 
    Document   : header
    Created on : 25-May-2023, 10:34:55
    Author     : Hoang Long
--%>

<div class="container-fluid">

    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="home" class="text-decoration-none">
                <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">Ria</span>Shop</h1>
            </a>

        </div>
        <div class="col-lg-6 col-6 text-left">
            <form action="search" method="post">
                <div class="input-group" >
                    <input  oninput="searchByName(this)" value="${search}" name="search" type="text" class="form-control" placeholder="Search for products">
                    <button onclick="this.form.submit()" style="background-color: transparent; border: 1px solid #EDF1FF;"  >
                        <div class="input-group-append" >
                            <span class="input-group-text bg-transparent text-primary" style="border: none;" >
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </button>
                    <div id="searchIn"></div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">

            <a href="cart" class="btn border">
                <i class="fas fa-shopping-cart text-primary"></i>
                <span class="badge" id="numberCart">${numberOfCart}</span>
            </a>
        </div>
    </div>
</div>
<script>
    function searchByName(param) {
        var txtSearch = param.value;
        console.log(txtSearch);
        $.ajax({
            url: "/project/hint-search",
            type: "get",
            data: {
                txtSearch: txtSearch
            },
            success: function (data) {
                var out = document.getElementById("searchIn");
                out.innerHTML = data;
            },
            error: function (xhr) {
                //handle error
            }
        });
    }
</script>

web/history-order.jsp
<%-- 
    Document   : chart-product
    Created on : 21-Jun-2023, 11:43:30
    Author     : Hoang Long
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="icon" href="img/icon.jpg" type="image/x-icon"/>
        <title>RiaShop- Your dream your world</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free HTML Templates" name="keywords">
        <meta content="Free HTML Templates" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="css/style.css" rel="stylesheet">
        <link href="css/stylePaging.css" rel="stylesheet">
    </head>
    <body>
        <%@include file="header-manage.jsp" %>
        <!-- Navbar Start -->
        <div class="container-fluid mb-5">
            <div class="row border-top px-xl-5">
                <div class="col-lg-3 d-none d-lg-block">
                    <%@include file="left-manager.jsp" %>
                </div>

                <div class="col-lg-9">
                    

                    <div class='row'>
                        

                        <div class="col-lg-12 table-responsive mb-12" style="margin-top: 15px">
                            <div class="input-group">
                                Year<input id="yearOrder" onkeypress="handle(event)"class="form-control" type="text" name="year">
                                Month<input id="monthOrder" onkeypress="handle(event)" class="form-control" type="text" name="month">
                                Day<input id="dayOrder" onkeypress="handle(event)" class="form-control" type="text" name="day">
                            </div>
                            <table class="table table-bordered text-center mb-0 list">
                                <thead class="bg-secondary text-dark list">
                                    <tr>
                                        <th>Order Id</th>
                                        <th>Customer Name</th>
                                        <th>Total Money</th>
                                        <th>Date</th>
                                        <th>Customer Location</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody class="align-middle " id="orderList">
                                <c:forEach items="${listOrder}" var="o">
                                    <tr class="item">
                                        <td>${o.oId}</td>
                                        <td>${o.customer.info.fullName}</td>
                                        <td>${o.totalMoney}</td>
                                        <td>${o.date}</td>
                                        <td>${o.customer.info.regionCountry}</td>
                                        <td>
                                            <button class="btn btn-sm btn-primary" onclick="viewDetail(${o.oId},${sessionScope.acc.id})">
                                                View Detail
                                            </button>
                                        </td>
                                    </tr>
                                </c:forEach>
                            </tbody>
                        </table>
                        <div class="col-12 pb-1 ">
                            <nav aria-label="Page navigation">
                                <ul class="listPage">

                                </ul>
                            </nav>
                        </div>
                    </div>
                    <table class="table table-bordered text-center mb-0">
                        <thead class="bg-secondary text-dark list">
                            <tr>
                                <th>Order Id</th>
                                <th>Product Name</th>
                                <th>Material</th>
                                <th>Size</th>
                                <th>Quantity</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody class="align-middle " id="orderDetail">

                        </tbody>   

                    </table>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>           
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
                                                function handle(e) {
                                                    if (e.keyCode === 13) {
                                                        e.preventDefault(); // Ensure it is only this code that runs
                                                        var year = document.getElementById('yearOrder').value;
                                                        var month = document.getElementById('monthOrder').value;
                                                        var day = document.getElementById('dayOrder').value;
                                                        $.ajax({
                                                            url: "/project/search-order-customer",
                                                            type: "get",
                                                            data: {
                                                                year: year,
                                                                month: month,
                                                                day: day,
                                                                cusId: ${sessionScope.acc.id}
                                                            },
                                                            success: function (data) {
                                                                var out = document.getElementById("orderList");
                                                                out.innerHTML = data;
                                                            },
                                                            error: function (xhr) {
                                                                //handle error
                                                            }
                                                        });
                                                    }
                                                }
                                                function viewDetail(oId, cId) {
                                                    console.log(oId + "==" + cId);
                                                    $.ajax({
                                                        url: "/project/view-detail-customer",
                                                        type: "get",
                                                        data: {
                                                            oId: oId,
                                                            cId: cId
                                                        },
                                                        success: function (data) {
                                                            var out = document.getElementById("orderDetail");
                                                            out.innerHTML = data;
                                                            loadItem();
                                                        },
                                                        error: function (xhr) {
                                                            //handle error
                                                        }
                                                    });
                                                }
                                                let thisPage = 1;
                                                let limit = 6;
                                                let list = document.querySelectorAll('.list .item');
                                                function loadItem() {
                                                    let beginGet = limit * (thisPage - 1);
                                                    let endGet = limit * thisPage - 1;
                                                    list.forEach((item, key) => {
                                                        if (key >= beginGet && key <= endGet) {
                                                            item.style.display = 'table-row';
                                                        } else {
                                                            item.style.display = 'none';
                                                        }
                                                    });
                                                    listPage();
                                                }
                                                loadItem();
                                                function listPage() {
                                                    let count = Math.ceil(list.length / limit);
                                                    document.querySelector('.listPage').innerHTML = '';
                                                    if (list.length == 0) {
                                                        let notFound = document.createElement('h1');
                                                        notFound.innerHTML = 'Not found any items';
                                                        notFound.style = 'text-align: center;align-items: center;color: #6F6F6F;';
                                                        notFound.classList.add('page-item');
                                                        document.querySelector('.right').appendChild(notFound);
                                                    }
                                                    if (thisPage != 1 && list.length != 0) {
                                                        let prev = document.createElement('li');
                                                        prev.innerHTML = '<<';
                                                        prev.setAttribute('onclick', "changePage(" + (thisPage - 1) + ")");
                                                        prev.classList.add('page-item');
                                                        document.querySelector('.listPage').appendChild(prev);
                                                    }

                                                    for (i = 1; i <= count; i++) {
                                                        let newPage = document.createElement('li');
                                                        newPage.innerText = i;
                                                        if (i == thisPage) {
                                                            newPage.classList.add('active');
                                                        }
                                                        newPage.classList.add('page-item');
                                                        newPage.setAttribute('onclick', "changePage(" + i + ")");
                                                        document.querySelector('.listPage').appendChild(newPage);
                                                    }

                                                    if (thisPage != count && list.length != 0) {
                                                        let next = document.createElement('li');
                                                        next.innerText = '>>';
                                                        next.setAttribute('onclick', "changePage(" + (thisPage + 1) + ")");
                                                        next.classList.add('page-item');
                                                        document.querySelector('.listPage').appendChild(next);
                                                    }

                                                }

                                                function changePage(i) {
                                                    thisPage = i;
                                                    loadItem();
                                                }



        </script>
    </body>
</html>